<div>
    <table>
        <thead>
            <tr>
                <th>Pseudo</th>
                <th>Role</th>
                <th>Created At</th>
                <th>Verified</th>
                <th>Modify roles</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($datas as $d): ?>
            <tr>
                <td><?= $d['pseudo']?></td>
                <td><?= $d['roles']?></td>
                <td><?= $d['create_at']?></td>
                <td><?= $d['is_verified']?></td>
                <td><a href='index.php?page=admin&action=modifyUser&name=<?= $d['pseudo']?>'>Modify</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>