<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/projet_tchat/assets/style/app.css">
    <title>Document</title>
</head>
<!-- C:\wamp64\www\Projet_tchat\assets\style\style.css -->
<body>
    <header>
        <nav>
            <a href="index.php?page=home"><img src="assets/src/img/logo.jpg" alt="" class="logo"></a>
            <?php if (empty($_SESSION['user_id']) && empty($_SESSION['user_name'])): ?>
                <div>
                    <a href="index.php?page=home">Home</a>
                    <a href="index.php?page=login&action=index">Login</a>
                    <a href="index.php?page=login&action=register">Register</a>
                </div>

            <?php else: ?>
                <div>
                    <a href="index.php?page=home">Home</a>
                    <a href="index.php?page=channel&action=index">Channel</a>
                    <a href="index.php?page=login&action=logout">Logout</a>
                </div>
            <?php endif ?>
        </nav>
    </header>
    <main>
        <?php if (isset($nameFile) && $nameFile): ?>
            <?php require './views/' . $nameFile . '/' . $template . '.phtml' ?>
        <?php else: ?>
            <?php require './views/' . $template . '.phtml' ?>
        <?php endif ?>
    </main>
    <script src="assets/js/script.js"></script>
</body>

</html>