<div>
    <p class="red">Voici tous les Channels et salons de discussion</p>
    <?php if ($_SESSION): ?>
        <?php if ($_SESSION['roles'] === "ROLES_ADMIN"): ?>
            <a href="?page=admin&action=index"> Créer un channel ou un salon</a>
        <?php endif; ?>
    <?php endif; ?>

    <?php if (!empty($category)): ?>
        <?php foreach ($categories as $catName => $salons): ?>
            <h2><?= htmlspecialchars($catName) ?></h2>

            <?php if (!empty($salons)): ?>
                <ul>
                    <?php foreach ($salons as $salon): ?>
                        <li><a href="?page=channel&action=show&name=<?=htmlspecialchars($salon) ?>"><?= htmlspecialchars($salon) ?></a></li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <p><em>Aucun salon pour cette catégorie.</em></p>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>