<div>
    <p class="red">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus ex molestias sint natus possimus aliquam dolor ea unde hic, quibusdam quidem, vel adipisci quaerat dolorum. Tenetur explicabo voluptatibus sint vel expedita doloremque itaque nihil eum fugiat consequatur, molestiae sapiente! Ratione itaque cumque maxime accusantium modi voluptatibus ipsa repellendus commodi repellat!</p>
    <?php if ($_SESSION): ?>
        <p>Bonjour, <?= $_SESSION['user_name'] ?></p>


        <?php if ($_SESSION['roles'] === 'ROLES_ADMIN'): ?>
            <p> Vous êtes bien connecter en tant que administrateur !</p>
        <?php endif; ?>
    <?php endif; ?>
</div>